// Lights Out: 5x5 grid, click toggles cell + 4 orthogonal neighbors.
// Goal: turn all lights off. Solvable initial state is generated by
// applying N random toggles to an all-off grid (toggle is self-inverse,
// so the resulting configuration is guaranteed reachable).

import { defineGame } from '@shared/game-module';
import { safeRead, safeWrite } from '@shared/storage';
import { showOverlay as showOverlayEl, hideOverlay as hideOverlayEl } from '@shared/overlay';
import { createGenToken } from '@shared/gen-token';

const SIZE = 5;
const STORAGE_BEST = 'lights-out.best';
const SCRAMBLE_MIN = 8;
const SCRAMBLE_MAX = 12;
const WIN_DELAY_MS = 420;

type GameState = 'playing' | 'won';

let boardEl!: HTMLElement;
let movesEl!: HTMLElement;
let bestEl!: HTMLElement;
let restartBtn!: HTMLButtonElement;
let overlay!: HTMLElement;
let overlayTitle!: HTMLElement;
let overlayMsg!: HTMLElement;
let overlayRestart!: HTMLButtonElement;

let grid: boolean[] = new Array(SIZE * SIZE).fill(false);
let cellEls: HTMLButtonElement[] = [];
let moves = 0;
let best: number | null = null;
let state: GameState = 'playing';

const gen = createGenToken();

function loadBest(): number | null {
  const v = safeRead<number>(STORAGE_BEST, 0);
  return Number.isFinite(v) && v > 0 ? v : null;
}

function saveBest(): void {
  if (best !== null) safeWrite(STORAGE_BEST, best);
}

function idx(r: number, c: number): number {
  return r * SIZE + c;
}

function toggleAt(g: boolean[], r: number, c: number): void {
  if (r < 0 || r >= SIZE || c < 0 || c >= SIZE) return;
  g[idx(r, c)] = !g[idx(r, c)];
}

function applyMove(g: boolean[], r: number, c: number): void {
  toggleAt(g, r, c);
  toggleAt(g, r - 1, c);
  toggleAt(g, r + 1, c);
  toggleAt(g, r, c - 1);
  toggleAt(g, r, c + 1);
}

function allOff(g: boolean[]): boolean {
  for (let i = 0; i < g.length; i++) if (g[i]) return false;
  return true;
}

function scramble(): boolean[] {
  const g: boolean[] = new Array(SIZE * SIZE).fill(false);
  const moveCount =
    SCRAMBLE_MIN + Math.floor(Math.random() * (SCRAMBLE_MAX - SCRAMBLE_MIN + 1));
  for (let i = 0; i < moveCount; i++) {
    const r = Math.floor(Math.random() * SIZE);
    const c = Math.floor(Math.random() * SIZE);
    applyMove(g, r, c);
  }
  if (allOff(g)) {
    applyMove(g, 2, 2);
  }
  return g;
}

function buildBoard(): void {
  boardEl.innerHTML = '';
  cellEls = [];
  for (let r = 0; r < SIZE; r++) {
    for (let c = 0; c < SIZE; c++) {
      const btn = document.createElement('button');
      btn.type = 'button';
      btn.className = 'cell';
      btn.setAttribute('role', 'gridcell');
      btn.setAttribute('aria-label', `Hücre ${r + 1},${c + 1}`);
      btn.dataset.r = String(r);
      btn.dataset.c = String(c);
      btn.addEventListener('click', onCellClick);
      boardEl.appendChild(btn);
      cellEls.push(btn);
    }
  }
}

function renderGrid(): void {
  for (let i = 0; i < cellEls.length; i++) {
    const el = cellEls[i]!;
    const on = grid[i]!;
    el.classList.toggle('cell--on', on);
    el.setAttribute('aria-pressed', on ? 'true' : 'false');
  }
}

function renderMoves(): void {
  movesEl.textContent = String(moves);
}

function renderBest(): void {
  bestEl.textContent = best === null ? '—' : String(best);
}

function onCellClick(e: MouseEvent): void {
  if (state !== 'playing') return;
  const target = e.currentTarget as HTMLButtonElement | null;
  if (!target) return;
  const r = Number(target.dataset.r);
  const c = Number(target.dataset.c);
  if (!Number.isInteger(r) || !Number.isInteger(c)) return;

  applyMove(grid, r, c);
  moves++;
  renderMoves();
  renderGrid();

  if (allOff(grid)) {
    state = 'won';
    const winMoves = moves;
    const myGen = gen.current();
    window.setTimeout(() => {
      if (!gen.isCurrent(myGen)) return;
      showWin(winMoves);
    }, WIN_DELAY_MS);
  }
}

function showWin(winMoves: number): void {
  const isBest = best === null || winMoves < best;
  if (isBest) {
    best = winMoves;
    saveBest();
    renderBest();
  }
  overlayTitle.textContent = isBest ? 'Yeni rekor!' : 'Tüm ışıklar kapandı!';
  overlayMsg.textContent = `${winMoves} hamlede çözdün.`;
  showOverlayEl(overlay);
  overlayRestart.focus({ preventScroll: true });
}

function hideOverlay(): void {
  hideOverlayEl(overlay);
}

function startGame(): void {
  gen.bump();
  state = 'playing';
  grid = scramble();
  moves = 0;
  hideOverlay();
  renderMoves();
  renderBest();
  renderGrid();
}

function init(): void {
  boardEl = document.querySelector<HTMLElement>('#board')!;
  movesEl = document.querySelector<HTMLElement>('#moves')!;
  bestEl = document.querySelector<HTMLElement>('#best')!;
  restartBtn = document.querySelector<HTMLButtonElement>('#restart')!;
  overlay = document.querySelector<HTMLElement>('#overlay')!;
  overlayTitle = document.querySelector<HTMLElement>('#overlay-title')!;
  overlayMsg = document.querySelector<HTMLElement>('#overlay-msg')!;
  overlayRestart = document.querySelector<HTMLButtonElement>('#overlay-restart')!;

  best = loadBest();

  restartBtn.addEventListener('click', startGame);
  overlayRestart.addEventListener('click', startGame);

  window.addEventListener('keydown', (e) => {
    if (e.key === 'r' || e.key === 'R') {
      startGame();
      e.preventDefault();
    } else if (e.key === 'Enter' && state === 'won') {
      startGame();
      e.preventDefault();
    }
  });

  buildBoard();
  startGame();
}

export const game = defineGame({ init, reset: startGame });
