// Lights Out: 5x5 grid, click toggles cell + 4 orthogonal neighbors.
// Goal: turn all lights off. Solvable initial state is generated by
// applying N random toggles to an all-off grid (toggle is self-inverse,
// so the resulting configuration is guaranteed reachable).

const SIZE = 5;
const STORAGE_BEST = 'lights-out.best';
const SCRAMBLE_MIN = 8;
const SCRAMBLE_MAX = 12;
const WIN_DELAY_MS = 420; // wait for the last fade-out before showing overlay

type GameState = 'playing' | 'won';

const boardEl = document.querySelector<HTMLElement>('#board')!;
const movesEl = document.querySelector<HTMLElement>('#moves')!;
const bestEl = document.querySelector<HTMLElement>('#best')!;
const restartBtn = document.querySelector<HTMLButtonElement>('#restart')!;
const overlay = document.querySelector<HTMLElement>('#overlay')!;
const overlayTitle = document.querySelector<HTMLElement>('#overlay-title')!;
const overlayMsg = document.querySelector<HTMLElement>('#overlay-msg')!;
const overlayRestart =
  document.querySelector<HTMLButtonElement>('#overlay-restart')!;

let grid: boolean[] = new Array(SIZE * SIZE).fill(false);
let cellEls: HTMLButtonElement[] = [];
let moves = 0;
let best: number | null = loadBest();
let state: GameState = 'playing';

// Generation token guards async win callback from a stale game.
let gen = 0;

function safeReadNumber(key: string): number | null {
  try {
    const raw = localStorage.getItem(key);
    if (raw === null) return null;
    const n = Number(raw);
    return Number.isFinite(n) && n > 0 ? n : null;
  } catch {
    return null;
  }
}

function safeWriteNumber(key: string, value: number): void {
  try {
    localStorage.setItem(key, String(value));
  } catch {
    /* ignore (private mode, full disk, disabled, etc.) */
  }
}

function loadBest(): number | null {
  return safeReadNumber(STORAGE_BEST);
}

function saveBest(): void {
  if (best !== null) safeWriteNumber(STORAGE_BEST, best);
}

function idx(r: number, c: number): number {
  return r * SIZE + c;
}

function toggleAt(g: boolean[], r: number, c: number): void {
  if (r < 0 || r >= SIZE || c < 0 || c >= SIZE) return;
  g[idx(r, c)] = !g[idx(r, c)];
}

function applyMove(g: boolean[], r: number, c: number): void {
  toggleAt(g, r, c);
  toggleAt(g, r - 1, c);
  toggleAt(g, r + 1, c);
  toggleAt(g, r, c - 1);
  toggleAt(g, r, c + 1);
}

function allOff(g: boolean[]): boolean {
  for (let i = 0; i < g.length; i++) if (g[i]) return false;
  return true;
}

function scramble(): boolean[] {
  // Start from solved state, apply random moves. Every resulting
  // configuration is guaranteed solvable. Avoid landing on all-off.
  const g: boolean[] = new Array(SIZE * SIZE).fill(false);
  const moveCount =
    SCRAMBLE_MIN + Math.floor(Math.random() * (SCRAMBLE_MAX - SCRAMBLE_MIN + 1));
  for (let i = 0; i < moveCount; i++) {
    const r = Math.floor(Math.random() * SIZE);
    const c = Math.floor(Math.random() * SIZE);
    applyMove(g, r, c);
  }
  if (allOff(g)) {
    // extremely unlikely but possible — toggle one center move to ensure
    // the board is actually a puzzle.
    applyMove(g, 2, 2);
  }
  return g;
}

function buildBoard(): void {
  boardEl.innerHTML = '';
  cellEls = [];
  for (let r = 0; r < SIZE; r++) {
    for (let c = 0; c < SIZE; c++) {
      const btn = document.createElement('button');
      btn.type = 'button';
      btn.className = 'cell';
      btn.setAttribute('role', 'gridcell');
      btn.setAttribute('aria-label', `Hücre ${r + 1},${c + 1}`);
      btn.dataset.r = String(r);
      btn.dataset.c = String(c);
      btn.addEventListener('click', onCellClick);
      boardEl.appendChild(btn);
      cellEls.push(btn);
    }
  }
}

function renderGrid(): void {
  for (let i = 0; i < cellEls.length; i++) {
    const el = cellEls[i]!;
    const on = grid[i]!;
    el.classList.toggle('cell--on', on);
    el.setAttribute('aria-pressed', on ? 'true' : 'false');
  }
}

function renderMoves(): void {
  movesEl.textContent = String(moves);
}

function renderBest(): void {
  bestEl.textContent = best === null ? '—' : String(best);
}

function onCellClick(e: MouseEvent): void {
  if (state !== 'playing') return;
  const target = e.currentTarget as HTMLButtonElement | null;
  if (!target) return;
  const r = Number(target.dataset.r);
  const c = Number(target.dataset.c);
  if (!Number.isInteger(r) || !Number.isInteger(c)) return;

  applyMove(grid, r, c);
  moves++;
  renderMoves();
  renderGrid();

  if (allOff(grid)) {
    // Lock further input immediately so spam-clicks during the fade
    // can't increment moves past the winning count.
    state = 'won';
    const winMoves = moves;
    const myGen = gen;
    window.setTimeout(() => {
      if (myGen !== gen) return; // user restarted during the fade
      showWin(winMoves);
    }, WIN_DELAY_MS);
  }
}

function showWin(winMoves: number): void {
  const isBest = best === null || winMoves < best;
  if (isBest) {
    best = winMoves;
    saveBest();
    renderBest();
  }
  overlayTitle.textContent = isBest ? 'Yeni rekor!' : 'Tüm ışıklar kapandı!';
  overlayMsg.textContent = `${winMoves} hamlede çözdün.`;
  overlay.classList.remove('overlay--hidden');
  overlay.setAttribute('aria-hidden', 'false');
  // Move focus to the prominent "new game" button so keyboard users can
  // restart with Enter immediately.
  overlayRestart.focus({ preventScroll: true });
}

function hideOverlay(): void {
  overlay.classList.add('overlay--hidden');
  overlay.setAttribute('aria-hidden', 'true');
}

function startGame(): void {
  // Bump generation so any pending win-timer from the previous game bails.
  gen++;
  state = 'playing';
  grid = scramble();
  moves = 0;
  hideOverlay();
  renderMoves();
  renderBest();
  renderGrid();
}

restartBtn.addEventListener('click', startGame);
overlayRestart.addEventListener('click', startGame);

window.addEventListener('keydown', (e) => {
  if (e.key === 'r' || e.key === 'R') {
    startGame();
    e.preventDefault();
  } else if (e.key === 'Enter' && state === 'won') {
    startGame();
    e.preventDefault();
  }
});

buildBoard();
startGame();
